const CommonConstants = {
    NOT_APPLICABLE : 'NOT_APPLICABLE',
    TEST_USER_NAME : 'Aakarsh Sinha',
    TEST_USER_ID : 'aakarsh.sinha',
    MYSELF : 'myself',
    SENDER : 'sender',
    RECIPIENT : 'recipient',
    TRANSACTION_ID : 'transactionId', 
    NAME : 'name', 
    TYPE : 'type', 
    AMOUNT : 'amount', 
    PLATFORM : 'platform', 
    MODE : 'mode', 
    CATEGORY : 'category', 
    BANK_NAME : 'bankName',
    BANK_CODE_NAME : 'bankCodeName',
    COUNTRY : 'country',
    CURRENCY_NAME : 'currencyName',
    CURRENCY_CODE : 'currencyCode',
    BALANCE : 'balance',
    TRANSFER : 'transfer',
    EXPENSE : 'expense',
    INCOME : 'income',
    QUANTITY : 'quantity',
    FEE : 'fee',
    AVG_ENTRY_PRICE : 'avgEntryPrice',
    BASE_TOKEN : 'baseToken',
    MAIN_TOKEN : 'mainToken',
    BUY : "buy",
    SELL : "sell",
    USER_ID : 'userId',
    TOKEN : 'token',
    CODE : 'code'
}

module.exports = CommonConstants;